In [5]:
%load_ext autoreload
%autoreload 1

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [33]:
%aimport GraphState
import torch
import torch_geometric
import numpy as np

from GraphState import GraphState
from torch_geometric.data import Data

In [64]:
K3 = Data(
    x = torch.eye(3),
    edge_index = torch.Tensor(
        [[0, 0, 1, 1, 2, 2],
         [1, 2, 0, 2, 0, 1]]
    )
)

env = GraphState(K3)

print(f"Vertices:\n{env.graph.x}\n\nEdge Indices:\n{env.graph.edge_index}\n\nCurrent Vertex:\n{env.curr_vertex}")

print("\n---- Step to Vertex 0 ----\n")
env, reward, isDone, isTruncated = env.step(0)
print(f"Vertices:\n{env.graph.x}\n\nEdge Indices:\n{env.graph.edge_index}\n\nCurrent Vertex:\n{env.curr_vertex}\n\nIs Done: {isDone}\n\nIs Truncated: {isTruncated}")

print("\n---- Step to Vertex 1 ----\n")
env, reward, isDone, isTruncated = env.step(1)
print(f"Vertices:\n{env.graph.x}\n\nEdge Indices:\n{env.graph.edge_index}\n\nCurrent Vertex:\n{env.curr_vertex}\n\nIs Done: {isDone}\n\nIs Truncated: {isTruncated}")

print("\n---- Step to Vertex 2 ----\n")
env, reward, isDone, isTruncated = env.step(2)
print(f"Vertices:\n{env.graph.x}\n\nEdge Indices:\n{env.graph.edge_index}\n\nCurrent Vertex:\n{env.curr_vertex}\n\nIs Done: {isDone}\n\nIs Truncated: {isTruncated}")

Vertices:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Edge Indices:
tensor([[0., 0., 1., 1., 2., 2.],
        [1., 2., 0., 2., 0., 1.]])

Current Vertex:
tensor([0., 0., 0.])

---- Step to Vertex 0 ----

Vertices:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Edge Indices:
tensor([[0., 0., 1., 1., 2., 2.],
        [1., 2., 0., 2., 0., 1.]])

Current Vertex:
tensor([1., 0., 0.])

Is Done: False

Is Truncated: False

---- Step to Vertex 1 ----

Vertices:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Edge Indices:
tensor([[1., 2.],
        [2., 1.]])

Current Vertex:
tensor([0., 1., 0.])

Is Done: False

Is Truncated: False

---- Step to Vertex 2 ----

Vertices:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Edge Indices:
tensor([], size=(2, 0))

Current Vertex:
tensor([0., 0., 1.])

Is Done: True

Is Truncated: False


In [65]:
K3 = Data(
    x = torch.eye(3),
    edge_index = torch.Tensor(
        [[0, 0, 1, 1, 2, 2],
         [1, 2, 0, 2, 0, 1]]
    )
)

env = GraphState(K3)
print("---- Step to Vertex 0 ----")
env, reward, isDone, isTruncated = env.step(0)
print("---- Step to Vertex 1 ----")
env, reward, isDone, isTruncated = env.step(1)
print("---- Step to Vertex 0 ----")
env, reward, isDone, isTruncated = env.step(0) # NOTE: Should throw an exception

---- Step to Vertex 0 ----
---- Step to Vertex 1 ----
---- Step to Vertex 0 ----


RuntimeError: Tried to step to a non-adjacent vertex